-- Update problem statements with 200-300 word dummy English text
-- Round 1 Problems (A-E)

UPDATE public.problems 
SET statement = 'In the fragmented memory banks of CodeVerse, a catastrophic data corruption event has scattered critical binary sequences across multiple sectors. Your mission is to reconstruct the original data structure from these corrupted fragments. Given an array of integers where each element represents a fragment of the original sequence, you must apply logical operations to restore the complete pattern. The reconstruction process involves analyzing relationships between adjacent elements, identifying repeating patterns, and applying appropriate transformations to merge fragments correctly. Consider edge cases where fragments may be incomplete or contain noise. Your solution must handle various input sizes efficiently, from small sequences of ten elements to massive datasets containing thousands of fragments. The challenge tests your understanding of array manipulation, pattern recognition, and algorithmic efficiency. Pay attention to memory constraints and optimize your approach for both time and space complexity. The success of your reconstruction will determine whether the CodeVerse system can recover from this critical failure.'
WHERE round_number = 1 AND problem_code = 'A';

UPDATE public.problems 
SET statement = 'The logic gate network that powers the core computational infrastructure has experienced widespread failures, leaving critical decision-making circuits inoperable. You are tasked with diagnosing and repairing these malfunctioning gates by analyzing their boolean expressions and determining satisfiability conditions. Each gate implements a complex boolean function expressed in conjunctive normal form (CNF), where multiple clauses must all be satisfied simultaneously for the gate to function correctly. Your challenge involves determining whether valid input combinations exist that can satisfy all clauses, thus restoring gate functionality. The complexity increases with the number of variables and clauses, requiring sophisticated constraint-solving techniques. Consider cases where no solution exists, indicating permanent gate failure requiring replacement. Efficient algorithms are crucial as the network contains thousands of interconnected gates, each potentially contributing to cascading failures if not properly diagnosed. Your solution must scale to handle large boolean formulas while maintaining reasonable computation time.'
WHERE round_number = 1 AND problem_code = 'B';

UPDATE public.problems 
SET statement = 'Memory fragmentation has left the system with two partially sorted memory blocks that must be merged into a single coherent sequence for proper system operation. These blocks represent critical data structures that have been corrupted during a recent system crash, and their restoration is essential for system recovery. Your task is to efficiently combine these blocks while maintaining proper sort order, minimizing computational overhead, and preserving all data integrity. The merge operation must handle edge cases such as empty blocks, blocks with duplicate values, and blocks of vastly different sizes. Consider the most efficient merge strategy given the constraints of available memory and processing power. Your algorithm should be robust enough to handle real-time system requirements where these merge operations may occur frequently during normal system operation. Optimization is key, as inefficient merging could cause system slowdowns or memory overflow errors that could further destabilize the already fragile CodeVerse infrastructure.'
WHERE round_number = 1 AND problem_code = 'C';

UPDATE public.problems 
SET statement = 'A recursive function responsible for calculating critical sequence values has lost its termination conditions during a code corruption event, causing infinite recursion and system instability. The function was originally designed to compute a mathematical sequence where each value depends on previous values according to a well-defined recurrence relation. Your challenge is to restore the function''s base cases and implement an efficient computation method that can handle large input values without causing stack overflow or excessive computation time. The sequence follows the pattern where each element is derived from its predecessors, creating dependencies that must be resolved in the correct order. Consider multiple approaches: naive recursion with proper base cases, memoization to avoid redundant calculations, or iterative bottom-up dynamic programming for maximum efficiency. The solution must handle edge cases including zero, negative inputs (if applicable), and extremely large values that would cause traditional recursive approaches to fail. Your implementation will determine whether the system can resume normal operation or requires complete shutdown and restart procedures.'
WHERE round_number = 1 AND problem_code = 'D';

UPDATE public.problems 
SET statement = 'The encryption subsystem has detected an anomaly in its key generation algorithm, where cryptographic keys are not being generated with sufficient entropy to maintain security standards. You must analyze the key generation process and implement a solution that ensures each generated key meets minimum security requirements. The problem involves detecting patterns in key generation that could lead to predictable or weak keys, then modifying the algorithm to increase randomness and unpredictability. Consider factors such as seed values, random number generation quality, and proper handling of cryptographic primitives. Your solution must maintain backward compatibility with existing encrypted data while improving security for future operations. The implementation should include validation checks to verify that generated keys meet specified strength criteria, with appropriate error handling for cases where key generation fails. Performance is important, as the system requires rapid key generation for real-time operations, but security cannot be compromised for speed. Your fix must prevent potential security vulnerabilities that could expose the entire CodeVerse system to unauthorized access.'
WHERE round_number = 1 AND problem_code = 'E';

-- Round 2 Problems (A-E)

UPDATE public.problems 
SET statement = 'Temporal anomalies have disrupted the fundamental flow of time within the CodeVerse simulation, creating paradoxes where events occur out of sequence and causality becomes unpredictable. Your task is to analyze a sequence of temporal events, each with its own timestamp and dependency requirements, and determine whether a valid chronological ordering exists that satisfies all temporal constraints. The challenge lies in detecting and resolving circular dependencies where event A requires event B to occur first, but event B similarly requires event A, creating an impossible temporal loop. These paradoxes threaten to destabilize the entire simulation if left unresolved. You must develop an algorithm that can detect such cycles while also finding valid orderings when they exist. The problem requires understanding of graph theory, topological sorting, and conflict resolution strategies. Consider edge cases including events with no dependencies, events with multiple dependencies, and events that depend on themselves. Your solution must be efficient enough to process large numbers of temporal events in real-time, as delays in resolving these paradoxes could cause cascading failures throughout the system. The fate of the entire CodeVerse timeline rests on your ability to restore proper temporal ordering.'
WHERE round_number = 2 AND problem_code = 'A';

UPDATE public.problems 
SET statement = 'The quantum processing unit has entered an unstable superposition state, with multiple possible computational outcomes existing simultaneously until observation causes state collapse. You are observing a system of N quantum states, each represented by a complex probability amplitude that determines the likelihood of that state being observed when measurement occurs. Your challenge involves calculating the probability of each possible outcome using quantum mechanics principles, specifically the squared magnitude of probability amplitudes. The system''s behavior follows quantum mechanical rules where amplitudes can interfere constructively or destructively, affecting final probabilities in non-intuitive ways. You must correctly handle complex number arithmetic, including proper calculation of magnitudes and phases. The problem tests your understanding of quantum probability theory and your ability to implement precise numerical computations with complex numbers. Consider edge cases such as states with zero amplitude, states with equal probabilities, and systems approaching classical behavior. Your calculations must maintain sufficient precision to accurately predict measurement outcomes, as errors could lead to incorrect predictions about system behavior. The stability of quantum computations throughout CodeVerse depends on your accurate analysis of these superposition states.'
WHERE round_number = 2 AND problem_code = 'B';

UPDATE public.problems 
SET statement = 'Entropy within the system is increasing at an alarming rate, causing information structures to degrade and lose their organization. You are given a string representing the current state of system entropy, where each character represents a different information unit. The system''s natural tendency is to maximize entropy by randomizing character positions, but adjacent characters can only swap if they are different. Your mission is to calculate the minimum number of swap operations required to reach maximum entropy state, defined as a configuration where no two adjacent characters are identical. If achieving maximum entropy is impossible given the initial character distribution, you must return an appropriate indicator. The problem requires analyzing character frequencies and their distributions to determine feasibility of the goal state. Consider cases where certain characters are too numerous to avoid adjacency, making maximum entropy unachievable. Your algorithm must efficiently handle strings of various lengths and character sets, from simple binary strings to complex multi-character alphabets. The challenge tests your understanding of combinatorics, graph theory (modeling valid swap sequences), and optimization strategies. Solving this entropy challenge is crucial for preventing complete system disorganization that could render CodeVerse inoperable.'
WHERE round_number = 2 AND problem_code = 'C';

UPDATE public.problems 
SET statement = 'A critical section of code has become trapped in an infinite temporal loop, where execution repeatedly returns to previous states without making progress. This loop exists across multiple time dimensions, making detection particularly challenging. You are given a directed graph representing temporal jump relationships between code execution states, where each node represents a state and each edge represents a possible temporal transition. Your task is to detect whether cycles exist in this temporal graph, and if cycles are found, determine the length of the shortest cycle. The presence of cycles indicates an infinite loop that must be broken to restore normal execution flow. However, breaking such loops incorrectly could cause the code to skip critical operations or lose important state information, potentially causing data corruption or system crashes. Your solution must accurately identify all cycles, not just the first one encountered, as multiple concurrent loops could exist. Consider graphs with no cycles, graphs with multiple cycles, and graphs where every path eventually leads to a cycle. The algorithm must be efficient enough to analyze complex execution graphs with thousands of states and transitions. Your detection and analysis of these temporal loops will determine whether the affected code sections can be repaired or must be completely rewritten, with significant implications for system stability and performance.'
WHERE round_number = 2 AND problem_code = 'D';

UPDATE public.problems 
SET statement = 'The synchronization mechanism that coordinates parallel processing threads has failed, causing race conditions and inconsistent state across multiple execution contexts. You must design and implement a solution that ensures proper thread synchronization while maintaining system performance and avoiding deadlock conditions. The problem involves managing access to shared resources where multiple threads must coordinate their operations to prevent conflicts. Your challenge includes detecting potential deadlock scenarios where threads are waiting for each other in circular dependencies, as well as implementing locking mechanisms that prevent data corruption while allowing maximum parallelism. Consider various synchronization primitives such as mutexes, semaphores, and atomic operations, choosing the most appropriate for each scenario. The solution must handle complex interaction patterns including nested locks, timeout conditions, and priority-based thread scheduling. Edge cases to consider include threads with different priority levels, systems with limited resources, and scenarios where some threads may terminate unexpectedly. Your implementation must balance between preventing race conditions and maintaining system responsiveness, as overly aggressive locking could cause performance degradation that rivals the original synchronization failure. The stability of all parallel processing within CodeVerse depends on your ability to restore proper thread coordination.'
WHERE round_number = 2 AND problem_code = 'E';

-- Round 3 Problems (A-E)

UPDATE public.problems 
SET statement = 'The first layer of the core logic system has been exposed, revealing a fundamental decryption challenge that guards access to deeper system levels. This initial barrier tests your understanding of cryptographic principles and your ability to reverse-engineer encryption algorithms without access to the original encryption keys. The challenge involves analyzing encrypted data patterns, identifying underlying structures, and developing decryption strategies that can recover the original information. The encryption method appears to use a combination of substitution and transposition techniques, possibly combined with additional obfuscation layers. Your task requires both theoretical knowledge of cryptography and practical problem-solving skills to break through this first defense. Consider various attack vectors including frequency analysis, pattern recognition, known plaintext attacks, and brute force approaches when appropriate. The problem may involve multiple stages where solving one part reveals information needed for subsequent stages. Time is a factor, as the system may have self-destruct mechanisms that activate if decryption attempts take too long. Your success here will determine whether you can proceed to deeper system layers or if you will be locked out permanently. The core logic awaits, but first you must prove your worth by overcoming this initial challenge that separates those with superficial knowledge from those with true expertise.'
WHERE round_number = 3 AND problem_code = 'A';

UPDATE public.problems 
SET statement = 'The second layer of core logic demands pattern recognition abilities that transcend simple linear thinking, requiring you to identify relationships and structures across multiple dimensions of data and computation. This challenge presents information in forms that are not immediately obvious, requiring you to think in terms of higher-dimensional spaces, abstract relationships, and non-obvious connections between seemingly unrelated elements. The patterns you must recognize may exist across time, across different data representations, or across multiple levels of system abstraction. Your ability to see beyond surface-level appearances and identify underlying structures will be tested thoroughly. Consider approaches such as dimensional analysis, graph-based pattern matching, statistical correlation detection, and machine learning-inspired pattern recognition techniques. The challenge may require you to transform data into different representations to reveal hidden patterns that are not visible in the original format. Multiple valid interpretations might exist, but only one leads to the correct solution path. The problem tests both your analytical capabilities and your creativity in approaching complex pattern recognition challenges. Success requires combining logical reasoning with intuitive pattern matching, possibly making connections that have never been explicitly stated but must be inferred from available information. This layer separates those who can only follow instructions from those who can truly understand and manipulate complex systems.'
WHERE round_number = 3 AND problem_code = 'B';

UPDATE public.problems 
SET statement = 'The third layer challenges your mastery of recursive structures and self-referential systems, where solutions must be built using techniques that mirror the problem''s own recursive nature. This challenge involves algorithms that call themselves, data structures that contain references to themselves, and problem-solving approaches where the solution to a larger problem depends on solutions to smaller instances of the same problem. Understanding recursion requires grasping how problems can be decomposed into smaller subproblems, how base cases provide termination conditions, and how recursive calls build up solutions incrementally. The challenge will test your ability to design recursive algorithms that are both correct and efficient, avoiding common pitfalls such as infinite recursion, excessive stack usage, or redundant computations. You may need to combine recursion with memoization or transform recursive solutions into iterative ones when performance demands it. The problem might involve nested recursive structures, mutual recursion where multiple functions call each other recursively, or recursive data structures like trees and graphs. Consider edge cases including empty structures, single-element cases, and deeply nested recursions that could cause stack overflow. The challenge also tests your ability to reason about recursive algorithms mathematically, proving correctness and analyzing time and space complexity. Mastery of this layer demonstrates that you truly understand how complex systems can be built from simple, self-referential rules, a fundamental concept in computational thinking.'
WHERE round_number = 3 AND problem_code = 'C';

UPDATE public.problems 
SET statement = 'The fourth layer represents the ultimate synthesis challenge, requiring you to combine all concepts and techniques from previous layers into a unified solution that addresses a problem of unprecedented complexity. This is not merely a test of individual skills, but a demonstration of your ability to integrate multiple problem-solving paradigms into a coherent whole. The challenge will require elements of decryption, pattern recognition, recursive thinking, and potentially additional concepts not yet encountered. Success here demands not just technical skill but also strategic thinking about how to approach complex, multi-faceted problems. You must decide which techniques to apply where, how to break the problem into manageable components, and how to verify that your integrated solution is correct. The problem may have multiple valid approaches, but some will be more elegant or efficient than others. Consider how solutions from different layers might interact or conflict, requiring careful coordination and possibly trade-offs between different optimization goals. The challenge tests your ability to work at a high level of abstraction while maintaining attention to implementation details. Time management becomes critical, as the complexity of this layer means that inefficient approaches could consume excessive time without yielding results. Your success in this synthesis challenge proves that you possess not just isolated skills, but the ability to think systematically about complex problems and integrate diverse solution strategies into effective implementations.'
WHERE round_number = 3 AND problem_code = 'D';

UPDATE public.problems 
SET statement = 'This is the final confrontation: the Impossible Script that has defeated countless challengers and stands as the ultimate test of computational mastery. Erevos-901, the Great Compiler, watches your every move, judging not just your solution but your approach, your creativity, and your understanding of the deepest principles that govern computation itself. The Impossible Script is not merely a difficult problem; it is a problem that seems to violate fundamental assumptions about what is computationally possible. It challenges you to think beyond established paradigms, to question assumptions that others take for granted, and to find solutions in spaces that appear empty of possibility. Success here requires more than technical skill; it demands intuition, persistence, and the courage to pursue approaches that seem unlikely or impossible. The problem may present itself in ways that deliberately mislead, requiring you to see through surface appearances to underlying truths. You may need to combine techniques in ways that have never been attempted, or discover new approaches entirely. The challenge tests every aspect of your problem-solving ability: logical reasoning, creative thinking, technical implementation, error handling, and performance optimization. Time is limited, pressure is high, and the stakes could not be greater. This is your moment to prove that you are not just another solver, but someone who can transcend limitations and achieve what others consider impossible. Erevos-901 awaits your solution. The fate of CodeVerse hangs in the balance. Show what you are truly capable of.'
WHERE round_number = 3 AND problem_code = 'E';

-- Update timer durations for Round 2 and Round 3 problems
UPDATE public.problems 
SET timer_duration_seconds = 660  -- 11 minutes
WHERE round_number = 2;

-- Update Round 3 global timer setting
UPDATE public.admin_settings 
SET setting_value = '3300'  -- 55 minutes in seconds
WHERE setting_key = 'round3_global_timer_seconds';

